# Docs https://alacritty.org/config-alacritty.html

# Dracula theme
import = ["~/.config/alacritty/dracula.toml"]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true

opacity = 0.95
#blur = true

option_as_alt = "OnlyLeft"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 7 }
#italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
#normal = { family = "FiraCode Nerd Font Mono", style = "Retina" }
size = 16.0

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = true

[cursor]
style = { shape = "Beam", blinking = "Always" }
